//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task_02.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Booking
    {
        public int booking_id { get; set; }

        [Display(Name = "Check-in")]
        
        public string from_date { get; set; }

        [Display(Name = "Check-out")]
        
        public string to_date { get; set; }

        [Display(Name = "Number of Nigths")]
        
        public int no_of_night_stay { get; set; }

        [Display(Name = "Number of Adults")]
       
        public int no_of_adults { get; set; }

        [Display(Name = "Number of Children")]
        
        public int no_of_children { get; set; }

        [Display(Name = "Price")]
        
        public int price { get; set; }

        [Display(Name = "Status")]
        public string book_status { get; set; }
        public int? hotel_id { get; set; }
        public string customer_id { get; set; }

        public string priceInAud { get { return String.Format("{0} AUD", this.price); } set { } }

        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Hotel Hotel { get; set; }
    }
    public class Book_Hotel
    {
        public Booking booking { get; set; }
        public Hotel hotel { get; set; }
        public Room room { get; set; }
    }
}
