//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task_02.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Room
    {
        [Required]
        public int Id { get; set; }

        [Required]
        public string RoomNumber { get; set; }

        [Required]
        public string Type { get; set; }

        [Required]
        public int PricePerNight { get; set; }

        [Required]
        public int Rating { get; set; }
        public int HotelId { get; set; }

        [Required]
        public string Path { get; set; }

        [Required]
        public string Status { get; set; }
    
        public virtual Hotel Hotel { get; set; }
    }
}
